--- #YAML:1.0
name:               Bundle-Net-Frame
version:            1.02
abstract:           A bundle to install various Net::Frame related modules
author:
    - GomoR <gomor-cpan_at_gomor.org>
license:            artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
